// lang.js - فایلی تایبەت بە زمانەکان و وەرگێڕان

const translations = {
    ku: {
        title: "ERBIL OFFICE - IHEC",
        subtitle: "سیستەمی هاتن و دەرچوونی فەرمانبەران",
        emailLabel: "ئیمەیڵ (Email)",
        passLabel: "تێپەڕ وشە (Password)",
        loginBtnText: "چوونە ژوورەوە",
        waitText: "چاوەڕێ بکە...",
        errorEmpty: "تکایە ئیمەیڵ و پاسوۆرد بنووسە!",
        login_error: "ئیمەیڵ یان وشەی تێپەڕ هەڵەیە!",
        logout: "چوونە دەرەوە",
        employee: "فەرمانبەر",
        admin: "بەڕێوەبەر",
        clockLoading: "باردەکرێت...",
        arrival: "ئامادەبوون",
        device: "ئامێر",
        location: "لۆکەیشن",
        verifying: "پشکنین...",
        checkin: "ئامادە بوون",
        checkout: "دەرچوون",
        history: "مێژووی هاتن و دەرچوونەکانت",
        month: "مانگ",
        confirmTitle: "دڵنیایت؟",
        confirmMsg: "ئایا دەتەوێت ئەم کردارە ئەنجام بدەیت؟",
        no: "نەخێر",
        yes: "بەڵێ، دڵنیام",
        date: "ڕێکەوت",
        close: "داخستن",
        at: "لە",
        verified: "ناسراوە",
        unverified: "نەناسراوە",
        suitable: "گونجاوە",
        notSuitable: "لۆکەیشن گونجاو نییە",
        gpsWeak: "شوێن ورد نییە",
        searching: "چاوەڕوانبە...",
        errorFetch: "هەڵە لە پشکنین",
        distBranch: "دووری لە بنکە",
        limit: "سنوور",
        gpsAcc: "وردی GPS",
        confInTitle: "تۆمارکردنی هاتن",
        confInMsg: "ئایا دڵنیایت لە تۆمارکردنی ئامادەبوونی ئێستات؟",
        confOutTitle: "تۆمارکردنی دەرچوون",
        confOutMsg: "ئایا دڵنیایت دەتەوێت دەرچوون تۆمار بکەیت؟",
        msgLocErr: "هەڵە: زانیاری لۆکەیشن یان بەکارهێنەر بەردەست نییە.",
        msgBranchErr: "هەڵە: زانیاری بنکەی کارکردن بەردەست نییە.",
        msgAccErr: "هەڵە: وردی لۆکەیشنەکەت گونجاو نییە. تکایە هەوڵ بدەرەوە.",
        msgOutsideErr: "هەڵە: تۆ لە دەرەوەی سنووری بنکەی کارکردنی خۆتیت.",
        msgOutLocErr: "هەڵە: لۆکەیشنەکەت گونجاو نییە بۆ دەرچوون. تکایە هەوڵ بدەرەوە.",
        msgInSuccess: "ئامادەبوونت تۆمار کرا!",
        msgOutSuccess: "دەرچوونەکەت تۆمار کرا. کاتێکی خۆش!",
        recordNotFound: "هیچ تۆمارێک بۆ ئەم ڕۆژە نییە",
        retryBtn: "دووبارە پشکنین",
        notRecorded: "تۆمار نەکراوە", 
        months: ["کانوونی دووەم", "شوبات", "ئازار", "نیسان", "ئایار", "حوزەیران", "تەمموز", "ئاب", "ئەیلوول", "تشرینی یەکەم", "تشرینی دووەم", "کانوونی یەکەم"],
        weekdays: ["یەکشەممە", "دووشەممە", "سێشەممە", "چوارشەممە", "پێنجشەممە", "هەینی", "شەممە"],
        noLocSupport: "وێبگەڕەکەت لۆکەیشن پشتگیری ناکات",
        invalidDevice: "ئامێر نەناسراوە",
        noBranch: "زانیاری بنکە نییە",
        waitRecord: "تۆمارکردن...",
        deviceTaken: "ئامێری پێشوو نییە",
        alreadyCheckedIn: "تۆ پێشتر هاتنت تۆمار کردووە و دەرنەچوویت.",
        dailyLimitReached: "سوپاس بۆ پابەندی ئەمڕۆت ، کاتێکی خۆش!",
        updateTitle: "وەشانی نوێ بەردەستە",
        updateMsg: "چەندین گۆڕانکاری و چاکسازی نوێ ئەنجامدراوە بۆ باشترکردنی ئەزموونی بەکارهێنانت.",
        updateBtn: "ئێستا نوێی بکەرەوە",
        pwaTitle: "دابەزاندنی ئەپ",
        pwaDesc: "بۆ ئەزموونێکی باشتر و خێراتر، ئەپەکە بخەرە سەر شاشەی سەرەکی.",
        pwaInstall: "دابەزاندن",
        pwaIOSMsg: "کلیک لە 'Share' بکە و پاشان 'Add to Home Screen' هەڵبژێرە.",
        changeTheme: "گۆڕینی ڕەنگ (تێم)",
        justification: "ڕوونکردنەوەی فەرمی",
        mgmtSystem: "Management System",
        vpnError: "هەڵە: VPN چالاک کراوە! تکایە بیکوژێنەرەوە بۆ ئەوەی بتوانیت هاتن و دەرچوون تۆمار بکەیت.",
        adminDashboardTitle: "کۆمسیۆنی باڵای سەربەخۆی هەڵبژاردنەکان - هەولێر",
        adminDashboardTitleShort: "کۆمسیۆنی باڵا - ئۆفیسی هەولێر",
        generalOffice: "سیستەمی چاودێری دەوامی فەرمانبەران تایبەت بە ئۆفیسی پارێزگای هەولێر",
        generalOfficeShort: "سیستەمی چاودێری دەوامی فەرمانبەران لە هەولێر",
        adminLabel: " چاودێران :",
        earlyIn: "پێش 8:30 (هاتن)",
        midIn: "8:30 - 9:00 (هاتن)",
        veryLateInAdmin: "دوای 9:00 (هاتن)",
        absentStat: "نەهاتوو (Absent)",
        earlyOutAdmin: "پێش 2:30 (دەرچوون)",
        onTimeOutAdmin: "دوای 2:30 (دەرچوون)",
        noExitStat: "دەرنەچوو (No Exit)",
        searchName: "گەڕان بەپێی ناو",
        searchPlaceholder: "ناوی فەرمانبەر بنووسە...",
        branchLabel: "بنکە",
        allBranches: "هەموو بنکەکان",
        statusLabel: "دۆخی ئامادەبوون",
        allStatus: "هەموو دۆخەکان",
        printReport: "پرێنتکردن",
        attendanceListTitle: "لیستی فەرمانبەران",
        colName: "ناوی فەرمانبەر",
        colBranch: "بنکەی تۆمار",
        colTime: "کاتی (هاتن / دەرچوون)",
        colStatus: "دۆخی ئێستا",
        colClass: "پۆڵێن",
        colJust: "ڕوونکردنەوە",
        statusPresent: "ئامادەبوو",
        statusAbsent: "نەهاتوو",
        onDuty: "ئێستا لە دەوامدایە",
        showStats: "نیشاندانی ئامارەکان",
        hideStats: "شاردنەوەی ئامارەکان",
        showAttendanceList: "نیشاندانی لیستی ئامادەبووان",
        hideAttendanceList: "شاردنەوەی لیستی ئامادەبووان",
        countPerson: "کەس",
        noJustRecorded: "بۆ ئەم ڕێکەوتە هیچ ڕوونکردنەوەیەک نەنووسراوە.",
        justificationOf: "ڕوونکردنەوەی:",
        resetDevice: "ڕیسێتکردنی ئامێر",
        resetConfirmMsg: "ئایا دڵنیایت لە ڕیسێتکردنی ناسنامەی ئامێری ئەم فەرمانبەرە؟",
        resetSuccess: "ناسنامەی ئامێر بە سەرکەوتوویی ڕیسێت کرایەوە.",
        mockLocationError: "هەڵە: لۆکەیشنی ساختە (Fake GPS) دۆزرایەوە! تکایە ئەپەکان بکوژێنەرەوە.",
        saveJustification: "ناردنی ڕوونکردنەوە",
        editJustification: "دەستکاریکردنی ڕوونکردنەوە",
        justificationPlaceholder: "هۆکاری درەنگ هاتن یان زوو دەرچوونت لێرە بنووسە بۆ چاودێرانی سیستەمەکە...",
        justificationSuccess: "ڕوونکردنەوەکەت بە سەرکەوتوویی تۆمار کرا.",
        deleteJustification: "سڕینەوەی ڕوونکردنەوە",
        deleteConfirmMsg: "ئایا دڵنیایت لە سڕینەوەی ئەم ڕوونکردنەوەیە بە تەواوەتی؟",
        deleteSuccess: "ڕوونکردنەوەکە بە سەرکەوتوویی سڕایەوە",
        updateSuccess: "سەرکەوتوو بوو",
        print: "چاپکردن",
        printHeaderSub: "ئۆفیسی پارێزگای هەولێر - سیستەمی هاتن و دەرچوونی فەرمانبەران ",
        adminDeptManager: "بەرپرسی بەشی کارگێڕی",
        officeManagerSign: "بەڕێوەبەری ئۆفیس",
        copyrightText: "هەموو مافێك پارێزراوە بۆ ئۆفیسی پارێزگای هەولێر",
        developedBy: "بیرۆکە و پەرەپێدان ",
        tebini:"تێبینی"
    },
    ar: {
        title: "ERBIL OFFICE - IHEC",
        subtitle: " نظام الحضور والانصراف للموظفين",
        emailLabel: "البريد الإلكتروني (Email)",
        passLabel: "كلمة المرور (Password)",
        loginBtnText: "تسجيل الدخول",
        waitText: "يرجى الانتظار...",
        errorEmpty: "يرجى إدخال البريد الإلكتروني وكلمة المرور!",
        login_error: "البريد الإلكتروني أو كلمة المرور غير صحيحة!",
        logout: "تسجيل الخروج",
        employee: "موظف",
        admin: "مدير",
        clockLoading: "جاري التحميل...",
        arrival: "الحضور",
        device: "الجهاز",
        location: "الموقع",
        verifying: "جاري التحقق...",
        checkin: "تسجيل حضور",
        checkout: "انصراف",
        history: "سجل الحضور والانصراف",
        month: "الشهر",
        confirmTitle: "هل أنت متأكد؟",
        confirmMsg: "هل تريد إجراء هذه العملية؟",
        no: "لا",
        yes: "نعم، أنا متأكد",
        date: "التاريخ",
        close: "إغلاق",
        at: "في",
        verified: "معروف",
        unverified: "غير معروف",
        suitable: "مناسب",
        notSuitable: "الموقع غير مناسب",
        gpsWeak: "الموقع غير دقيق",
        searching: "انتظر قليلاً...",
        errorFetch: "خطأ في التحقق",
        distBranch: "المسافة عن المركز",
        limit: "الحد",
        gpsAcc: "دقة GPS",
        confInTitle: "تسجيل الحضور",
        confInMsg: "هل أنت متأكد من تسجيل حضورك الآن؟",
        confOutTitle: "تسجيل الانصراف",
        confOutMsg: "هل أنت متأكد من تسجيل انصرافك؟",
        msgLocErr: "خطأ: معلومات الموقع أو المستخدم غير متوفرة.",
        msgBranchErr: "خطأ: معلومات موقع العمل غير متوفرة.",
        msgAccErr: "خطأ: دقة موقعك غير كافية. يرجى المحاولة مرة أخرى.",
        msgOutsideErr: "خطأ: أنت خارج حدود موقع عملك.",
        msgOutLocErr: "خطأ: موقعك غير مناسب لتسجيل الانصراف. يرجى المحاولة مرة أخرى.",
        msgInSuccess: "تم تسجيل حضورك بنجاح!",
        msgOutSuccess: "تم تسجيل انصرافك. طاب يومك!",
        recordNotFound: "لا يوجد سجل لهذا اليوم",
        retryBtn: "إعادة التحقق",
        notRecorded: "لم يتم التسجيل", 
        months: ["يناير", "فبراير", "مارس", "أبريل", "مايو", "يونيو", "يوليو", "أغسطس", "سبتمبر", "أكتوبر", "نوفمبر", "ديسمبر"],
        weekdays: ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة", "السبت"],
        noLocSupport: "متصفحك لا يدعم الموقع",
        invalidDevice: "جهاز غير معروف",
        noBranch: "لا توجد معلومات عن الفرع",
        waitRecord: "جاري التسجيل...",
        deviceTaken: "الجهاز غير متوفر",
        alreadyCheckedIn: "لقد سجلت حضورك بالفعل ولم تسجل انصرافك بعد.",
        dailyLimitReached: "شكراً لالتزامك اليوم، طاب يومك!",
        updateTitle: "تحديث جديد متاح",
        updateMsg: "تم إجراء العديد من التغييرات والتحسينات الجديدة لتحسين تجربتك.",
        updateBtn: "تحديث الآن",
        pwaTitle: "تثبيت التطبيق",
        pwaDesc: "للحصول على تجربة أفضل وأسرع، قم بتثبيت التطبيق على شاشتك الرئيسية.",
        pwaInstall: "تثبيت",
        pwaIOSMsg: "اضغط على 'Share' ثم اختر 'Add to Home Screen'.",
        changeTheme: "تغيير المظهر",
        justification: "تبرير رسمي",
        mgmtSystem: "Management System",
        vpnError: "خطأ: تم اكتشاف VPN! يرجى إيقاف تشغيله لتتمكن من تسجيل الحضور والانصراف.",
        adminDashboardTitle: "اَلْمُفَوَّضِيَّةُ الْعُلْيَا الْمُسْتَقِلَّةُ لِلِانْتِخَابَاتِ - أَرْبِيل",
        adminDashboardTitleShort: "اَلْمُفَوَّضِيَّةُ الْعُلْيَا - مکتب أَرْبِيل",
        generalOffice: "نظام مراقبة دوام الموظفين خاص بمكتب محافظة أربيل",
        generalOfficeShort: "نظام مراقبة دوام الموظفين في أربيل",
        adminLabel: "المراقبون :",
        earlyIn: "قبل 8:30 (دخول)",
        midIn: "8:30 - 9:00 (دخول)",
        veryLateInAdmin: "بعد 9:00 (دخول)",
        absentStat: "غائب (Absent)",
        earlyOutAdmin: "قبل 2:30 (خروج)",
        onTimeOutAdmin: "بعد 2:30 (خروج)",
        noExitStat: "لم يخرج (No Exit)",
        searchName: "بحث بالاسم",
        searchPlaceholder: "اكتب اسم الموظف...",
        branchLabel: "المركز",
        allBranches: "كل المراكز",
        statusLabel: "حالة الحضور",
        allStatus: "كل الحالات",
        printReport: "طباعة التقرير",
        attendanceListTitle: "قائمة الموظفين",
        colName: "اسم الموظف",
        colBranch: "مركز التسجيل",
        colTime: "وقت (الدخول / الخروج)",
        colStatus: "الحالة الحالية",
        colClass: "التصنيف",
        colJust: "التبرير",
        statusPresent: "حاضر",
        statusAbsent: "غائب",
        onDuty: "موجود في الدوام حالياً",
        showStats: "إظهار الإحصائيات",
        hideStats: "إخفاء الإحصائيات",
        showAttendanceList: "إظهار قائمة الحضور",
        hideAttendanceList: "إخفاء قائمة الحضور",
        countPerson: "أشخاص",
        noJustRecorded: "لا يوجد تبرير مسجل لهذا التاريخ.",
        justificationOf: "تبرير:",
        resetDevice: "إعادة ضبط الجهاز",
        resetConfirmMsg: "هل أنت متأكد من إعادة ضبط معرف الجهاز لهذا الموظف؟",
        resetSuccess: "تم إعادة ضبط معرف الجهاز بنجاح.",
        mockLocationError: "خطأ: تم اكتشاف موقع وهمي (Fake GPS)! يرجى إيقاف تشغيل التطبيقات.",
        saveJustification: "إرسال التبرير",
        editJustification: "تعديل التبرير",
        justificationPlaceholder: "اكتب سبب تأخرك أو خروجك المبكر هنا لعرضه على نظام المراقبة...",
        justificationSuccess: "تم تسجيل التبرير بنجاح.",
        deleteJustification: "حذف التبرير",
        deleteConfirmMsg: "هل أنت متأكد من حذف هذا التبرير نهائياً؟",
        deleteSuccess: "تم حذف التبرير بنجاح",
        updateSuccess: "تم بنجاح",
        print: "طباعة",
        printHeaderSub: "مكتب محافظة أربيل - نظام الحضور والانصراف للموظفين",
        adminDeptManager: "مسؤول القسم الإداري",
        officeManagerSign: "مدير المكتب",
        copyrightText: "جميع الحقوق محفوظة لمكتب محافظة أربيل",
        developedBy: "التفکیر وَتَطْوِير",
        tebini:"ملاحظة"

    }
};

let currentLang = localStorage.getItem('lang') || 'ku';

function applyLanguage() {
    document.documentElement.lang = currentLang;
    const langBtn = document.getElementById('current-lang-text');
    const flag = document.getElementById('current-flag');
    
    if (langBtn && flag) {
        if (currentLang === 'ku') {
            langBtn.innerText = 'کوردی';
            if (flag.tagName === 'IMG') flag.src = 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Flag_of_Kurdistan.svg/40px-Flag_of_Kurdistan.svg.png';
            else flag.className = 'flag-icon flag-ku';
        } else {
            langBtn.innerText = 'العربية';
            if (flag.tagName === 'IMG') flag.src = 'https://flagcdn.com/w40/iq.png';
            else flag.className = 'flag-icon flag-ar';
        }
    }

    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        const translation = translations[currentLang][key];
        if (translation) {
            if ((el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') && el.hasAttribute('placeholder')) {
                el.placeholder = translation;
            } else if (el.hasAttribute('aria-label')) {
                el.setAttribute('aria-label', translation);
            } else if (el.hasAttribute('title')) {
                el.setAttribute('title', translation);
            } else {
                el.innerText = translation;
            }
        }
    });
}

function setLang(lang) { // Renamed from selectLanguage to setLang as per index.html
    currentLang = lang;
    localStorage.setItem('lang', currentLang);
    applyLanguage();
    if (document.getElementById('dropdown-options')) document.getElementById('dropdown-options').classList.remove('show');
    // ئاگادارکردنەوەی هەموو پەڕەکە کە زمان گۆڕاوە بۆ نوێکردنەوەی دەقە داینامیکییەکان
    window.dispatchEvent(new CustomEvent('languageChanged', { detail: lang }));
}

document.addEventListener('DOMContentLoaded', applyLanguage);