// lang.js - فایلی تایبەت بە زمانەکان و وەرگێڕان

const translations = {
    ku: {
        title: "ERBIL OFFICE - IHEC",
        subtitle: "سیستەمی هاتن و دەرچوونی فەرمانبەران",
        emailLabel: "ئیمەیڵ (Email)",
        passLabel: "تێپەڕ ووشە (Password)",
        loginBtnText: "چوونە ژوورەوە",
        waitText: "چاوەڕێ بکە",
        errorEmpty: "تکایە ئیمەیڵ و پاسوۆرد بنووسە!",
        login_error: "ئیمەیڵ یان وشەی تێپەڕ هەڵەیە!",
        logout: "چوونە دەرەوە",
        employee: "فەرمانبەر",
        "sub-admin": "بەرپرسی بنکە",
        "assistant-manager": "یاریدەدەری بەرپرسی بنکە",
        admin: "بەڕێوەبەر",
        clockLoading: "باردەکرێت...",
        arrival: "ئامادەبوون",
        device: "ئامێر",
        location: "لۆکەیشن",
        verifying: "پشکنین...",
        checkin: "ئامادە بوونت تۆمار بکە",
        checkout: "دەرچوونت تۆمار بکە",
        history: "مێژووی هاتن و دەرچوونەکانت",
        month: "مانگ",
        confirmTitle: "دڵنیایت؟",
        confirmMsg: "ئایا دەتەوێت ئەم کردارە ئەنجام بدەیت؟",
        no: "نەخێر",
        yes: "بەڵێ، دڵنیام",
        date: "ڕێکەوت",
        close: "داخستن",
        at: "لە",
        verified: "ناسراوە",
        unverified: "نەناسراوە",
        suitable: "گونجاوە",
        notSuitable: "لۆکەیشن گونجاو نییە",
        gpsWeak: "شوێن ورد نییە",
        searching: "چاوەڕوانبە...",
        errorFetch: "هەڵە لە پشکنین",
        distBranch: "دووری لە بنکە",
        limit: "سنوور",
        gpsAcc: "وردی GPS",
        confInTitle: "تۆمارکردنی هاتن",
        confInMsg: "ئایا دڵنیایت لە تۆمارکردنی ئامادەبوونی ئێستات؟",
        confOutTitle: "تۆمارکردنی دەرچوون",
        confOutMsg: "ئایا دڵنیایت دەتەوێت دەرچوون تۆمار بکەیت؟",
        msgLocErr: "هەڵە: زانیاری لۆکەیشن بەردەست نییە.",
        msgBranchErr: "هەڵە: زانیاری بنکەی کارکردن بەردەست نییە.",
        msgAccErr: "هەڵە: وردی لۆکەیشنەکەت گونجاو نییە. تکایە هەوڵ بدەرەوە.",
        msgOutsideErr: "هەڵە: تۆ لە دەرەوەی سنووری بنکەی کارکردنی خۆتیت.",
        msgOutLocErr: "هەڵە: لۆکەیشنەکەت گونجاو نییە بۆ دەرچوون. تکایە هەوڵ بدەرەوە.",
        msgInSuccess: "ئامادەبوونت تۆمار کرا!",
        msgOutSuccess: "دەرچوونەکەت تۆمار کرا. کاتێکی خۆش!",
        recordNotFound: "هیچ تۆمارێک بۆ ئەم ڕۆژە نییە",
        retryBtn: "دووبارە پشکنین",
        notRecorded: "تۆمار نەکراوە", 
        months: ["کانوونی دووەم", "شوبات", "ئازار", "نیسان", "ئایار", "حوزەیران", "تەمموز", "ئاب", "ئەیلوول", "تشرینی یەکەم", "تشرینی دووەم", "کانوونی یەکەم"],
        weekdays: ["یەکشەممە", "دووشەممە", "سێشەممە", "چوارشەممە", "پێنجشەممە", "هەینی", "شەممە"],
        noLocSupport: "وێبگەڕەکەت لۆکەیشن پشتگیری ناکات",
        invalidDevice: "ئامێر نەناسراوە",
        noBranch: "زانیاری بنکە نییە",
        waitRecord: "تۆمارکردن...",
        deviceTaken: "ئەم ئامێرە پێشتر لەلایەن فەرمانبەرێکی ترەوە بەکارهێنراوە و تۆمار کراوە.",
        deviceTakenShort: "پێشتر بەکارهاتووە",
        notPreviousDevice: "ئامێری پێشوو نییە",
        notPreviousDevicelong: "هەمان ئامێری پێشوو نییە تکایە بگەڕێرەوە سەر ئامێری پێشوو تا بتوانیت تۆمارکردنەکانت ئەنجام بدەیت.",
        alreadyCheckedIn: "تۆ پێشتر هاتنت تۆمار کردووە و دەرنەچوویت.",
        dailyLimitReached: "سوپاس بۆ پابەندی ئەمڕۆت ، کاتێکی خۆش!",
        updateTitle: "وەشانی نوێ بەردەستە",
        updateMsg: "چەندین گۆڕانکاری و چاکسازی نوێ ئەنجامدراوە بۆ باشترکردنی ئەزموونی بەکارهێنانت.",
        updateBtn: "ئێستا نوێی بکەرەوە",
        pwaTitle: "دابەزاندنی ئەپ",
        pwaDesc: "بۆ ئەزموونێکی باشتر و خێراتر، ئەپەکە بخەرە سەر شاشەی سەرەکی.",
        pwaInstall: "دابەزاندن",
        pwaIOSMsg: "کلیک لە 'Share' بکە و پاشان 'Add to Home Screen' هەڵبژێرە.",
        changeTheme: "گۆڕینی ڕەنگ (تێم)",
        justification: "ڕوونکردنەوە",
        mgmtSystem: "Management System",
        vpnError: "هەڵە: VPN چالاک کراوە! تکایە بیکوژێنەرەوە بۆ ئەوەی بتوانیت هاتن و دەرچوون تۆمار بکەیت.",
        iosPrivateRelay: "هەڵە: iCloud Private Relay چالاکە! تکایە لە ڕێکخستنەکانی ئایفۆن بیکوژێنەرەوە بۆ ئەوەی بتوانیت بەردەوام بیت.",
        adminDashboardTitle: "کۆمسیۆنی باڵای سەربەخۆی هەڵبژاردنەکان - هەولێر",
        adminDashboardTitleShort: "کۆمسیۆنی باڵا - ئۆفیسی هەولێر",
        generalOffice: "سیستەمی تۆمارکردنی هاتن و دەرچوونی فەرمانبەرانی بنکەکانی تۆمار",
        generalOfficeShort: "سیستەمی هاتن و دەرچوونی فەرمانبەران",
        adminLabel: " چاودێران :",
        earlyIn: "پێش 9:00 (هاتن)",
        midIn: "مۆڵەتەکان (Leaves)",
        veryLateInAdmin: "دوای 9:00 (هاتن)",
        absentStat: "نەهاتوو (Absent)",
        earlyOutAdmin: "پێش 2:30 (دەرچوون)",
        onTimeOutAdmin: "دوای 2:30 (دەرچوون)",
        noExitStat: "دەرنەچوو (No Exit)",
        searchName: "گەڕان بەپێی ناو",
        searchPlaceholder: "ناوی فەرمانبەر بنووسە...",
        branchLabel: "بنکە",
        allBranches: "هەموو بنکەکان",
        statusLabel: "دۆخی ئامادەبوون",
        allStatus: "هەموو دۆخەکان",
        printReport: "پرێنتکردن",
        attendanceListTitle: "لیستی فەرمانبەران",
        colName: "ناوی فەرمانبەر",
        colBranch: "بنکەی تۆمار",
        colTime: "کاتی (هاتن / دەرچوون)",
        colStatus: "دۆخ",
        colClass: "پۆڵێن",
        collClass: "پلەی فەرمانبەر",
        colJust: "کۆنتڕۆڵ",
        statusPresent: "ئامادەبوو",
        statusAbsent: "نەهاتوو",
        onDuty: "کەس ئێستا لەدەوامە",
        showStats: "نیشاندانی ئامارەکان",
        hideStats: "شاردنەوەی ئامارەکان",
        showAttendanceList: "نیشاندانی لیستی ئامادەبووان",
        hideAttendanceList: "شاردنەوەی لیستی ئامادەبووان",
        countPerson: "کەس",
        noJustRecorded: "بۆ ئەم ڕێکەوتە هیچ ڕوونکردنەوەیەک نەنووسراوە.",
        justificationOf: "ڕوونکردنەوەی:",
        resetDevice: "ڕیسێتکردنی ئامێر",
        resetConfirmMsg: "ئایا دڵنیایت لە ڕیسێتکردنی ناسنامەی ئامێری ئەم فەرمانبەرە؟",
        resetSuccess: "ناسنامەی ئامێر بە سەرکەوتوویی ڕیسێت کرایەوە.",
        mockLocationError: "هەڵە: لۆکەیشنی ساختە (Fake GPS) دۆزرایەوە! تکایە ئەپەکان بکوژێنەرەوە.",
        saveJustification: "ناردنی ڕوونکردنەوە",
        editJustification: "دەستکاریکردنی ڕوونکردنەوە",
        justificationPlaceholder: "هۆکاری درەنگ هاتن یان زوو دەرچوونت لێرە بنووسە بۆ چاودێرانی سیستەمەکە...",
        justificationSuccess: "ڕوونکردنەوەکەت بە سەرکەوتوویی تۆمار کرا.",
        deleteJustification: "سڕینەوەی ڕوونکردنەوە",
        deleteConfirmMsg: "ئایا دڵنیایت لە سڕینەوەی ئەم ڕوونکردنەوەیە بە تەواوەتی؟",
        deleteSuccess: "ڕوونکردنەوەکە بە سەرکەوتوویی سڕایەوە",
        updateSuccess: "سەرکەوتوو بوو",
        print: "چاپکردن",
        printHeaderSub: "ئۆفیسی پارێزگای هەولێر - سیستەمی هاتن و دەرچوونی فەرمانبەران ",
        adminDeptManager: "بەرپرسی بەشی کارگێڕی",
        officeManagerSign: "بەڕێوەبەری ئۆفیس",
        copyrightText: "هەموو مافێك پارێزراوە بۆ ئۆفیسی پارێزگای هەولێر",
        developedBy: "بیرۆکە و پەرەپێدان ",
        tebini:"تێبینی",
        empSettings: "گۆڕانکاری",
        emppSettings: "ڕێکخستنەکانی فەرمانبەر"  ,
        changeBranch: "گۆڕینی بنکە",
        confirmBranchChange: "ئایا دڵنیایت لە گۆڕانکارییەکەت بۆ ئەم فەرمانبەرە؟",
        confirmBranchChangeFinal: "ئەمە کار دەکاتە سەر شوێنی دەوامی فەرمانبەرەکە، ئایا بۆ دواجار دڵنیایت؟",
        successUpdate: "گۆڕانکارییەکە بە سەرکەوتوویی ئەنجامدرا",
        change: "گۆڕین",
        leaveManagementt: "مۆڵەت",
        leaveManagement: "بەڕێوەبردنی مۆڵەت",
        startDate: "ڕێکەوتی دەستپێک",
        endDate: "ڕێکەوتی کۆتایی",
        reasonForLeave: "مۆڵەت",
        from: "لە",
        to: "بۆ",
        sickLeave: "مۆڵەتی نەخۆشی",
        maternityLeave: "مۆڵەتی دایکایەتی",
        longTermLeave: "مۆڵەتی درێژخایەن",
        regularLeave: "مۆڵەتی ئاسایی",
        hourlyLeave: "مۆڵەتی کاتی",
        mobileTeam: "تیمی گەڕۆك",
        workshop: "وەرشە",
        saveLeave: "تۆمارکردن",
        deleteLeave: "سڕینەوەی مۆڵەت",
        leaveStatus: "لە مۆڵەتە",
        noLeaveRecorded: "هیچ مۆڵەتێک تۆمار نەکراوە",
        confirmSaveLeave: "ئایا دڵنیایت لە تۆمارکردنی ئەم مۆڵەتە؟",
        confirmDeleteLeave: "ئایا دڵنیایت لە سڕینەوەی ئەم مۆڵەتە؟",
        leaveSavedSuccess: "مۆڵەت بە سەرکەوتوویی تۆمار کرا.",
        leaveDeletedSuccess: "مۆڵەت بە سەرکەوتوویی سڕایەوە.",
        selectLeaveReason: "هۆکاری مۆڵەت هەڵبژێرە",
        selectDates: "تکایە ڕێکەوتەکانی دەستپێک و کۆتایی دیاری بکە.",
        invalidDateRange: "ڕێکەوتی کۆتایی ناتوانێت پێش ڕێکەوتی دەستپێک بێت.",
        onLeave: "کەس لە مۆڵەتە",
        branchManagement: "بەڕێوەبردنی فەرمانبەرانی بنکە",
        selectStaff: "فەرمانبەر هەڵبژێرە",
        viewHistory: "هاتن و دەرچوونی ئەم فەرمانبەرە ببینە",
        staffAttendanceDetails: "وردەکاری دەوامی فەرمانبەر",
        filterByLeave: "فلتەر بەپێی جۆری مۆڵەت",
        exportExcel: "دەرهێنان بە (Excel)",
        weak: "لاواز",
        medium: "مامناوەند",
        strong: "بەهێز",
        veryStrong: "زۆر بەهێز",
        versionLabel: "وەشان",
        languageSection: "زمان (Language)",
        accountSecurity: "گۆڕینی تێپەڕ ووشە",
        currentPassword: "تێپەڕ ووشەی ئێستا (کۆن)",
        newPassword: "تێپەڕ ووشەی نوێ",
        confirmPassword: "دووپاتکردنەوەی تێپەڕ ووشەی نوێ",
        changePasswordBtn: "گۆڕینی تێپەڕ ووشە",
        passNotMatch: "هاوتا نییە",
        passMatch: "هاوتایە",
        manualCheckoutTab: "ناوچەی ترسناك",
        manualCheckoutBtn: "تۆمارکردنی دەرچوون بۆ ئێستا",
        confirmCheckoutPass: "تکایە تێپەڕەوشەی خۆت بنووسە بۆ دڵنیابوونەوە:",
        wrongPassword: "تێپەڕەوشە هەڵەیە! ناتوانیت ئەم کارە ئەنجام بدەیت.",
        after3pmOnly: "ئەم تایبەتمەندییە تەنها دوای کاتژمێر 3:00ی پاشنیوەڕۆ کارا دەبێت.",
        errorOldPass: "تکایە تێپەڕ ووشەی کۆن بنووسە",
        errorOldPassWrong: "تێپەڕ ووشەی کۆن هەڵەیە",
        passChangedSuccess: "تێپەڕ ووشە بە سەرکەوتوویی گۆڕدرا",
        complianceRate: "ڕێژەی پابەندی دەوام",
        dailyCompliance: "پابەندی ئەمڕۆ",
        arrivalCompliance: "پابەندی هاتن",
        departureCompliance: "پابەندی دەرچوون",
        statusPresentt: "ڕێژەی پابەندی",
        checkoutSuccessTitle: "سوپاس بۆ ئەمڕۆ",
        checkoutSuccessMsg: "کاتەکانی هاتن و دەرچوونت بە سەرکەوتوویی تۆمارکران.",
        yourCheckIn: "کاتی هاتن",
        yourCheckOut: "کاتی دەرچوون",
        yourCheckInn: "هاتن",
        yourCheckOutt: "دەرچوون",
        forgotPass: "ووشەی نهێنیت لە بیر چووە؟",
        resetPass: "ڕیسێتکردنی تێپەڕ ووشە",
        enterEmail: "ئیمەیڵەکەت بنووسە",
        sendCode: "ناردنی کۆد",
        verifyCode: "پشکنینی کۆد",
        enterOTP: "کۆدی نێردراو بنووسە",
        invalidOTP: "کۆدەکە هەڵەیە، تکایە دڵنیا بەرەوە!",
        newPass: "تێپەڕ ووشەی نوێ",
        confirmPass: "دووپاتکردنەوەی تێپەڕ ووشە",
        updatePass: "نوێکردنەوەی پاسوۆرد",
        passSuccess: "پاسوۆردەکەت بە سەرکەوتوویی گۆڕدرا!",
        emailNotFound: "ئەم ئیمەیڵە بوونی نییە لە سیستمدا!",
        codeExpires: "کۆدەکە بەسەردەچێت لە:",
        timeExpired: "کاتەکە تەواو بوو، تکایە دووبارە کۆد داوا بکەرەوە.",
        resendCode: "دووبارە ناردنەوە",
        weak: "لاواز",
        medium: "مامناوەند",
        strong: "بەهێز",
        veryStrong: "زۆر بەهێز",
        rateLimitError: "داواکاری زۆر نێردراوە! تکایە کاتژمێرێکی تر هەوڵ بدەرەوە.",
    },
    ar: {
        title: "ERBIL OFFICE - IHEC",
        subtitle: " نظام الحضور والانصراف للموظفين",
        emailLabel: "البريد الإلكتروني (Email)",
        passLabel: "كلمة المرور (Password)",
        loginBtnText: "تسجيل الدخول",
        waitText: "يرجى الانتظار",
        errorEmpty: "يرجى إدخال البريد الإلكتروني وكلمة المرور!",
        login_error: "البريد الإلكتروني أو كلمة المرور غير صحيحة!",
        logout: "تسجيل الخروج",
        employee: "موظف",
        "sub-admin": "مسؤول وحدة",
        "assistant-manager": "معاون مسؤول وحدة",
        admin: "مدير",
        clockLoading: "جاري التحميل...",
        arrival: "الحضور",
        device: "الجهاز",
        location: "الموقع",
        verifying: "جاري التحقق...",
        checkin: "تسجيل الحضور",
        checkout: "تسجيل الانصراف",
        history: "سجل الحضور والانصراف",
        month: "الشهر",
        confirmTitle: "هل أنت متأكد؟",
        confirmMsg: "هل تريد إجراء هذه العملية؟",
        no: "لا",
        yes: "نعم، أنا متأكد",
        date: "التاريخ",
        close: "إغلاق",
        at: "في",
        verified: "معروف",
        unverified: "غير معروف",
        suitable: "مناسب",
        notSuitable: "الموقع غير مناسب",
        gpsWeak: "الموقع غير دقيق",
        searching: "انتظر قليلاً...",
        errorFetch: "خطأ في التحقق",
        distBranch: "المسافة عن المركز",
        limit: "الحد",
        gpsAcc: "دقة GPS",
        confInTitle: "تسجيل الحضور",
        confInMsg: "هل أنت متأكد من تسجيل حضورك الآن؟",
        confOutTitle: "تسجيل الانصراف",
        confOutMsg: "هل أنت متأكد من تسجيل انصرافك؟",
        msgLocErr: "خطأ: معلومات الموقع أو المستخدم غير متوفرة.",
        msgBranchErr: "خطأ: معلومات موقع العمل غير متوفرة.",
        msgAccErr: "خطأ: دقة موقعك غير كافية. يرجى المحاولة مرة أخرى.",
        msgOutsideErr: "خطأ: أنت خارج حدود موقع عملك.",
        msgOutLocErr: "خطأ: موقعك غير مناسب لتسجيل الانصراف. يرجى المحاولة مرة أخرى.",
        msgInSuccess: "تم تسجيل حضورك بنجاح!",
        msgOutSuccess: "تم تسجيل انصرافك. طاب يومك!",
        recordNotFound: "لا يوجد سجل لهذا اليوم",
        retryBtn: "إعادة التحقق",
        notRecorded: "لم يتم التسجيل", 
        months: ["يناير", "فبراير", "مارس", "أبريل", "مايو", "يونيو", "يوليو", "أغسطس", "سبتمبر", "أكتوبر", "نوفمبر", "ديسمبر"],
        weekdays: ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة", "السبت"],
        noLocSupport: "متصفحك لا يدعم الموقع",
        invalidDevice: "جهاز غير معروف",
        noBranch: "لا توجد معلومات عن الفرع",
        waitRecord: "جاري التسجيل...",
        deviceTaken: "هذا الجهاز تم استخدامه مسبقاً من قبل موظف آخر ومسجل في النظام.",
        deviceTakenShort: "مستخدم سابقاً",
        notPreviousDevice: "ليس الجهاز السابق",
        notPreviousDevicelong: " هذا الجهاز ليس جهازك السابق، يرجى العودة إلى جهازك السابق لتتمكن من تسجيل حضورك وانصرافك.",
        alreadyCheckedIn: "لقد سجلت حضورك بالفعل ولم تسجل انصرافك بعد.",
        dailyLimitReached: "شكراً لالتزامك اليوم، طاب يومك!",
        updateTitle: "تحديث جديد متاح",
        updateMsg: "تم إجراء العديد من التغييرات والتحسينات الجديدة لتحسين تجربتك.",
        updateBtn: "تحديث الآن",
        pwaTitle: "تثبيت التطبيق",
        pwaDesc: "للحصول على تجربة أفضل وأسرع، قم بتثبيت التطبيق على شاشتك الرئيسية.",
        pwaInstall: "تثبيت",
        pwaIOSMsg: "اضغط على 'Share' ثم اختر 'Add to Home Screen'.",
        changeTheme: "تغيير المظهر",
        justification: "التوضيح",
        mgmtSystem: "Management System",
        vpnError: "خطأ: تم اكتشاف VPN! يرجى إيقاف تشغيله لتتمكن من تسجيل الحضور والانصراف.",
        iosPrivateRelay: "خطأ: iCloud Private Relay مفعل! يرجى إيقافه من إعدادات الآيفون لتتمكن من المتابعة.",
        adminDashboardTitle: "اَلْمُفَوَّضِيَّةُ الْعُلْيَا الْمُسْتَقِلَّةُ لِلِانْتِخَابَاتِ - مَكْتَب أَرْبِيل",
        adminDashboardTitleShort: "اَلْمُفَوَّضِيَّةُ الْعُلْيَا - مکتب أَرْبِيل",
        generalOffice: "نظام تسجيل الحضور والانصراف للموظفين في وحدات مراکز التسجيل",
        generalOfficeShort: "نظام حضور وانصراف للموظفين",
        adminLabel: "المستخدم :",
        earlyIn: "قبل 9:00 (دخول)",
        midIn: "الإجازات (Leaves)",
        veryLateInAdmin: "بعد 9:00 (دخول)",
        absentStat: "غیاب (Absent)",
        earlyOutAdmin: "قبل 2:30 (خروج)",
        onTimeOutAdmin: "بعد 2:30 (خروج)",
        noExitStat: "لم يخرج (No Exit)",
        searchName: "بحث بالاسم",
        searchPlaceholder: "اكتب اسم الموظف...",
        branchLabel: "المركز",
        allBranches: "كل المراكز",
        statusLabel: "حالة الحضور",
        allStatus: "كل الحالات",
        printReport: "طباعة التقرير",
        attendanceListTitle: "قائمة الموظفين",
        colName: "اسم الموظف",
        colBranch: "وحدة مركز التسجيل",
        colTime: "وقت (الدخول / الخروج)",
        colStatus: "الحالة",
        colClass: "التصنيف",
        collClass: "مهام الموظف",
        colJust: "التحكم",
        statusPresent: "حاضر",
        statusAbsent: "غياب",
        onDuty: "الموظف في الدوام",
        showStats: "إظهار الإحصائيات",
        hideStats: "إخفاء الإحصائيات",
        showAttendanceList: "إظهار قائمة الحضور",
        hideAttendanceList: "إخفاء قائمة الحضور",
        countPerson: "أشخاص",
        noJustRecorded: "لا يوجد توضيح مسجل لهذا التاريخ.",
        justificationOf: "توضيح الـ:",
        resetDevice: "إعادة ضبط الجهاز",
        resetConfirmMsg: "هل أنت متأكد من إعادة ضبط معرف الجهاز لهذا الموظف؟",
        resetSuccess: "تم إعادة ضبط معرف الجهاز بنجاح.",
        mockLocationError: "خطأ: تم اكتشاف موقع وهمي (Fake GPS)! يرجى إيقاف تشغيل التطبيقات.",
        saveJustification: "إرسال التوضيح",
        editJustification: "تعديل التوضيح",
        justificationPlaceholder: "اكتب سبب تأخرك أو خروجك المبكر هنا لعرضه على نظام...",
        justificationSuccess: "تم تسجيل التوضيح بنجاح.",
        deleteJustification: "حذف التوضيح",
        deleteConfirmMsg: "هل أنت متأكد من حذف هذا التوضيح نهائياً؟",
        deleteSuccess: "تم حذف التوضيح بنجاح",
        updateSuccess: "تم بنجاح",
        print: "طباعة",
        printHeaderSub: "مكتب محافظة أربيل - نظام الحضور والانصراف للموظفين",
        adminDeptManager: "مسؤول القسم الإداري",
        officeManagerSign: "مدير المكتب",
        copyrightText: "جميع الحقوق محفوظة لمكتب محافظة أربيل",
        developedBy: "التفکیر وَتَطْوِير",
        tebini:"ملاحظة",
        empSettings: "تعديلات",
        emppSettings: "إعدادات الموظف"  ,
        changeBranch: "تغيير المركز",
        confirmBranchChange: " هل أنت متأكد من إجراء هذا التغيير لهذا الموظف؟",
        confirmBranchChangeFinal: "سيؤثر هذا على موقع دوام الموظف، هل أنت متأكد للمرة الأخيرة؟",
        successUpdate: "تم إجراء التغيير بنجاح",
        change: "تغيير",
        leaveManagementt: "إجازة",
        leaveManagement : "إدارة الإجازات",
        startDate: "تاريخ البدء",
        endDate: "تاريخ الانتهاء",
        reasonForLeave: "الإجازة",
        from: "من",
        to: "إلى",
        sickLeave: "إجازة مرضية",
        maternityLeave: "إجازة أمومة",
        longTermLeave: "إجازة طويلة",
        regularLeave: "إجازة اعتيادية",
        hourlyLeave: "إجازة زمنية",
        mobileTeam: "الفرقة الجوالة",
        workshop: "ورشة",
        saveLeave: "حفظ",
        deleteLeave: "حذف الإجازة",
        leaveStatus: "في إجازة",
        noLeaveRecorded: "لم يتم تسجيل أي إجازة.",
        confirmSaveLeave: "هل أنت متأكد من تسجيل هذه الإجازة؟",
        confirmDeleteLeave: "هل أنت متأكد من حذف هذه الإجازة؟",
        leaveSavedSuccess: "تم تسجيل الإجازة بنجاح.",
        leaveDeletedSuccess: "تم حذف الإجازة بنجاح.",
        selectLeaveReason: "اختر نوع الإجازة",
        selectDates: "يرجى تحديد تاريخي البدء والانتهاء.",
        invalidDateRange: "تاريخ الانتهاء لا يمكن أن يكون قبل تاريخ البدء.",
        onLeave: "الموظف في إجازة",
        branchManagement: "إدارة موظفي المركز",
        selectStaff: "اختر الموظف",
        viewHistory: " سجل الحضور والانصراف لهذا الموظف",
        staffAttendanceDetails: "تفاصيل دوام الموظف",
        filterByLeave: "تصفية حسب نوع الإجازة",
        exportExcel: "تصدير (Excel)",
        weak: "ضعيف",
        medium: "متوسط",
        strong: "قوي",
        veryStrong: "قوي جداً",
        versionLabel: "الإصدار",
        languageSection: "اللغة (Language)",
        accountSecurity: "تغيير كلمة المرور",
        currentPassword: "كلمة المرور الحالية (القديمة)",
        newPassword: "كلمة المرور الجديدة",
        confirmPassword: "تأكيد كلمة المرور الجديدة",
        changePasswordBtn: "تغيير كلمة المرور",
        passNotMatch: "غير متطابق",
        passMatch: "متطابق",
        manualCheckoutTab: "منطقة الخطر",
        manualCheckoutBtn: "تسجيل الانصراف الآن",
        confirmCheckoutPass: "يرجى إدخال كلمة المرور الخاصة بك للتأكيد:",
        wrongPassword: "كلمة المرور غير صحيحة! لا يمكنك إجراء هذه العملية.",
        after3pmOnly: "هذه الميزة متاحة فقط بعد الساعة 3:00 مساءً.",
        errorOldPass: "يرجى إدخال كلمة المرور القديمة",
        errorOldPassWrong: "كلمة المرور القديمة غير صحيحة",
        passChangedSuccess: "تم تغيير كلمة المرور بنجاح",
        complianceRate: "نسبة الالتزام بالدوام",
        dailyCompliance: "التزام اليوم",
        arrivalCompliance: "التزام الحضور",
        departureCompliance: "التزام الانصراف",
        statusPresentt: "نسبة الالتزام",
        checkoutSuccessTitle: "شكراً لالتزامك اليوم",
        checkoutSuccessMsg: " تم تسجيل أوقات حضورك وانصرافك بنجاح.",
        yourCheckIn: "وقت الحضور",
        yourCheckOut: "وقت الانصراف",
        yourCheckInn: "الحضور",
        yourCheckOutt: "الانصراف",
        forgotPass: "نسيت كلمة المرور؟",
        resetPass: "استعادة كلمة المرور",
        enterEmail: "أدخل بريدك الإلكتروني",
        sendCode: "إرسال الرمز",
        verifyCode: "تحقق من الرمز",
        enterOTP: "أدخل الرمز المرسل إليك",
        invalidOTP: "الرمز غير صحيح، يرجى التأكد!",
        newPass: "كلمة مرور جديدة",
        confirmPass: "تأكيد كلمة المرور",
        updatePass: "تحديث كلمة المرور",
        passSuccess: "تم تغيير كلمة المرور بنجاح!",
        emailNotFound: "هذا البريد الإلكتروني غير موجود!",
        codeExpires: "تنتهي صلاحية الرمز في:",
        timeExpired: "انتهى الوقت، يرجى طلب رمز جديد.",
        resendCode: "إعادة الإرسال",
        weak: "ضعيف",
        medium: "متوسط",
        strong: "قوي",
        veryStrong: "قوي جداً",
        rateLimitError: "تم إرسال الكثير من الطلبات! يرجى المحاولة بعد ساعة.",
    }
};

let currentLang = localStorage.getItem('lang') || 'ku';

function applyLanguage() {
    document.documentElement.lang = currentLang;
    const langBtn = document.getElementById('current-lang-text');
    const flag = document.getElementById('current-flag');
    
    if (langBtn && flag) {
        if (currentLang === 'ku') {
            langBtn.innerText = 'کوردی';
            if (flag.tagName === 'IMG') flag.src = 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Flag_of_Kurdistan.svg/40px-Flag_of_Kurdistan.svg.png';
            else flag.className = 'flag-icon flag-ku';
        } else {
            langBtn.innerText = 'العربية';
            if (flag.tagName === 'IMG') flag.src = 'https://flagcdn.com/w40/iq.png';
            else flag.className = 'flag-icon flag-ar';
        }
    }

    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        const translation = translations[currentLang][key];
        if (translation) {
            if ((el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') && el.hasAttribute('placeholder')) {
                el.placeholder = translation;
            } else if (el.hasAttribute('aria-label')) {
                el.setAttribute('aria-label', translation);
            } else if (el.hasAttribute('title')) {
                el.setAttribute('title', translation);
            } else {
                el.innerText = translation;
            }
        }
    });
}

function setLang(lang) { // Renamed from selectLanguage to setLang as per index.html
    currentLang = lang;
    localStorage.setItem('lang', currentLang);
    applyLanguage();
    if (document.getElementById('dropdown-options')) document.getElementById('dropdown-options').classList.remove('show');
    // ئاگادارکردنەوەی هەموو پەڕەکە کە زمان گۆڕاوە بۆ نوێکردنەوەی دەقە داینامیکییەکان
    window.dispatchEvent(new CustomEvent('languageChanged', { detail: lang }));
}

document.addEventListener('DOMContentLoaded', applyLanguage);